### ISSUE TITLE
Automatically run activator ui

### ISSUE THREAD

**Issue by JunoJunho** [cmoro-deusto/docker-play#6]
Hi,

I'm a newbee for this docker play-framework container.
I usually use play-framework using activator ui, but the docker file is written by CMD['/bin/bash'].

What do you think if I modify CMD script from /bin/bash to activator script such as CMD['activator', 'ui', '-Dhttp.address=0.0.0.0]

**Comment by cmoro-deusto** [comment]
Yes, this container is designed for developers that might want to issue other activator commands appart from "ui", that's why the command is defined to launch a bash shell to which you can connect once the container is up. Therefore, I won't modify the Dockerfile.

Nevertheless, if you start this container adding your own command at the end, it will override the CMD definition.

This should work (not tested):

```
sudo docker run --rm -it -v "/home/dordoka/Code:/home/play/Code" -p 9000:9000 -p 9999:9999 -p 8888:8888 dordoka/play-framework /opt/activator/bin/activator ui
```

Another option is for you to fork this repo and modify the Dockerfile to suit your needs.

Thanks
